/* eslint-disable react/prop-types */
// npm components
import Head from 'next/head';

// css
import 'styles/index.scss';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Institchu - Gino Rodolfo Cabullo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <Component {...pageProps} />
      </div>
    </>
  );
}

export default MyApp;
